spacecloud@spacecloud-ix10-em:~/test$ python benchmark.py -o log.txt

Testing actual data dataset with 1189617 samples...
Running GPU HDBSCAN...
[[ 1.44965731e+00  3.03634276e+03  2.73283048e+00  1.05892182e+01]
 [ 5.02970252e-01  3.07704863e+03  3.28546195e+00  1.16355483e+01]
 [ 3.41192995e-01  3.02442390e+03  6.55522456e-01  2.69930495e+00]
 [ 1.50025235e-01  3.05622226e+03 -1.92981520e-01  5.56926689e+00]
 [ 2.75061720e-01  3.08541524e+03  4.61377011e-01  8.05393866e+00]
 [ 2.71624125e-01  3.01153754e+03 -3.07492404e-01  7.21990504e+00]
 [ 1.08414389e-01  3.03387431e+03 -3.13499149e-01  7.39383753e+00]
 [ 1.42059120e+00  3.05155422e+03  1.53984917e+00  9.90165485e+00]
 [ 2.10611329e-01  3.02263386e+03  9.77253935e-01  5.62392588e+00]
 [ 1.74776493e-01  3.07114412e+03 -6.94150051e-02  8.66311346e+00]]
temp_input_2361.txt
1.4496573132052175,3036.342761441189,2.7328304791512963,10.589218219011537
0.5029702515362275,3077.048625927318,3.2854619489630954,11.635548282794606
0.341192994790254,3024.423897233873,0.655522455748333,2.6993049523286423
0.1500252346872224,3056.222257569916,-0.1929815195960427,5.569266885621496
0.275061720459201,3085.415236095286,0.461377010889159,8.053938655447658
0.2716241250612017,3011.5375410417264,-0.3074924038218146,7.219905039362289
X.shape[1]:  4
GPU HDBSCAN failed: Command '['./gpu_hdbscan_edited/build/gpu_hdbscan', '--dimensions', '4', '--minpts', '5', '--input', 'temp_input_2361.txt', '--distMetric', '2', '--minclustersize', '50']' returned non-zero exit status 1.
Running sklearn HDBSCAN...
^Z
[3]+  Stopped                 python benchmark.py -o log.txt
spacecloud@spacecloud-ix10-em:~/test$ 